class Config:
    SCALE=600
    MAX_SCALE=1200
    TEXT_PROPOSALS_WIDTH=16
    MIN_NUM_PROPOSALS = 2
    # PROPOSALS的宽高比
    MIN_RATIO=0.5
    # 合成后的矩形框得分
    LINE_MIN_SCORE=0.7
    MAX_HORIZONTAL_GAP=50
    # 每个PROPOSALS的得分
    TEXT_PROPOSALS_MIN_SCORE=0.85
    # nms阈值
    TEXT_PROPOSALS_NMS_THRESH=0.2
    MIN_V_OVERLAPS=0.7
    MIN_SIZE_SIM=0.7


